language: python

python: "3.8"

services: postgres

addons:
	postgresql: "12"

env:
	- DJANGO 3.1 
	- DB=postgres

install:
	- pip install -r requirements.txt

before_script:
	- psql -c 'CREATE DATABASE travis_ci_test;' -U postgres


script:
	- python manage.py test
