version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./site/:/phsite/
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    image: postgres:12.0-apline
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pmhalvor
      - POSTGRES_PASSWORD=AsimovIsaac.73
      - POSTGRES_DB=sitedb

volumes:
  postgres_data:
