FROM python:3.11-slim

WORKDIR /new_radio

# COPY requirements.txt ./
# RUN pip install --no-cache-dir -r requirements.txt

# COPY new_radio/*.py ./

# ENV FLASK_ENV=production
# ARG PORT=5001
# ENV PORT=${PORT}

# EXPOSE ${PORT}

# CMD ["sh", "-c", "gunicorn -b 0.0.0.0:${PORT} app:app"]