version: '3.8'

services:
  web:
    build: .
    command: gunicorn phsite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./site/:/phsite/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data: