services:
  new_home:
    build:
      context: .
      dockerfile: Dockerfile.home
    container_name: new_home
    image: ghcr.io/pmhalvor/website:${TAG}
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      DEBUG: "false"
    platform: linux/amd64
