# Generated by Django 3.1.4 on 2020-12-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100, verbose_name='title')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('post_html', models.CharField(max_length=1000000, verbose_name='file')),
            ],
        ),
    ]
