# Generated by Django 3.1.4 on 2020-12-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201214_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('descr', models.CharField(max_length=200, verbose_name='description')),
                ('upload', models.FileField(upload_to='files/')),
            ],
        ),
    ]
