# Generated by Django 3.1.4 on 2020-12-20 00:05

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201219_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='_file',
            new_name='file_loc',
        ),
        migrations.RenameField(
            model_name='update',
            old_name='_img',
            new_name='img_loc',
        ),
        migrations.AddField(
            model_name='update',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 0, 5, 38, 84608, tzinfo=timezone.get_current_timezone()), verbose_name='pub_date'),
            preserve_default=False,
        ),
    ]
