# Generated by Django 3.1.4 on 2020-12-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201220_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('descr', models.CharField(max_length=200, verbose_name='description')),
                ('file_loc', models.URLField(verbose_name='url')),
                ('img_loc', models.ImageField(default='img/lookingcolors.jpg', upload_to='img/')),
                ('pub_date', models.DateTimeField(verbose_name='pub_date')),
            ],
        ),
        migrations.AlterField(
            model_name='update',
            name='title',
            field=models.CharField(max_length=30, verbose_name='title'),
        ),
    ]
