# Generated by Django 3.1.4 on 2020-12-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201223_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='file_loc',
            field=models.FileField(upload_to='notes/'),
        ),
    ]
