# Generated by Django 3.1.4 on 2020-12-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201223_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='update',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
