# Generated by Django 3.1.4 on 2021-01-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201223_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('descr', models.CharField(max_length=200, verbose_name='description')),
                ('file_loc', models.URLField(verbose_name='url')),
                ('img_loc', models.ImageField(default='img/lookingcolors.jpg', upload_to='img/')),
                ('pub_date', models.DateTimeField(verbose_name='pub_date')),
            ],
        ),
    ]
