# Generated by Django 3.1.4 on 2021-01-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='file_loc',
            new_name='url',
        ),
    ]
