# Generated by Django 3.1.4 on 2021-02-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=23, verbose_name='track_id')),
                ('played_at', models.DateTimeField(verbose_name='played_at')),
                ('artist', models.CharField(max_length=150, verbose_name='artist')),
                ('track', models.CharField(max_length=150, verbose_name='track')),
            ],
        ),
    ]
