name: Build and Push Docker Compose Image

on:
  push:
    # run on pushes to master or pushes that create tags starting with "v"
    branches:
      - master
    tags:
      - 'v*'   # triggers workflow for tags like "v1.0.0", adjust as needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx. This step creates a buildx builder instance.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Make empty .env file to avoid error in GHA
      - name: Create empty .env file
        run: |
          echo "" >> .env

      # Build the image using docker-compose (with platform option, if set in your compose file)
      - name: Build image via docker-compose
        run: docker compose build

      # Push the image(s) defined in docker-compose.yml to the registry
      - name: Push image via docker-compose
        run: docker compose push
